# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

def testing_pods
    pod 'Quick'
    pod 'Nimble'
end

target 'BddCounter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BddCounter

  target 'BddCounterTests' do
    inherit! :search_paths
    # Pods for testing
    testing_pods
  end

  target 'BddCounterUITests' do
    # Pods for testing
    testing_pods
  end

end
